import Head from 'next/head';
import Image from 'next/image';
import { useIntl } from 'react-intl';
import { useState, useEffect } from 'react';
import { Phone, Mail, Clock } from 'react-feather';

import WaveLarge from '../public/decorations/wave-large.png';
import WaveSmall from '../public/decorations/wave-small.png';

import { translate } from '../translations/Translations';
import styles from '../styles/Contact.module.css';

import { getContactInfo } from './api/services';
import { deviceBreakpoints } from '../utilities/config';
import { useWindowDimensions } from '../utilities/customHooks';
import { formatOpening } from '../utilities/customFunctions';

import Header from '../components/Header';
import Footer from '../components/Footer';

function Contact() {
    const intl = useIntl();

    const iconSize = 18;
    const { width, height } = useWindowDimensions();
    const [ sidebar, setSidebar ] = useState(false);

    const [ contacts, setContacts ] = useState([]);
    const ordering = contacts.find(item => item.id === 'ordering');
    const customer = contacts.find(item => item.id === 'customer');

    useEffect(() => {
        getContactInfo().then(content => setContacts(content));
    }, []);

    return (
        <div style={{ height: `${height}px`, width: '100vw', overflow: sidebar ? 'hidden' : 'visible', display: 'flex', flexDirection: 'column' }}>
            <Head>
                <title>Italian Tomato | Contact Us</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header open={sidebar} setOpen={setSidebar} />

            <main className={styles.container}>
                <section className={styles.content}>
                    <h1>{translate('page_title')}</h1>

                    <div>
                        {/* order hotline */}
                        <div>
                            <h4>{translate('ordering_title')}</h4>
                            <div className={styles.info}>
                                <p><Phone width={iconSize} /></p>
                                <p>{ordering?.phone}</p>
                            </div>
                            <div className={styles.info}>
                                <p><Mail width={iconSize} /></p>
                                <p>
                                    {ordering?.email}
                                    <span style={{ fontSize: '0.85em', marginTop: '-4px' }}>({translate('ordering_note')})</span>
                                </p>
                            </div>
                            <div className={styles.info}>
                                <p><Clock width={iconSize} /></p>
                                <p>{intl.locale === 'en' ? 
                                    ordering?.open.map((item, i) => (
                                        <span key={i}>{formatOpening(i, item)}</span>
                                    )) 
                                    : 
                                    ordering?.open_zh.map((item, i) => (
                                        <span key={i}>{item}</span>
                                    ))}
                                </p>
                            </div>
                        </div>

                        {/* customer hotline */}
                        <div>
                            <h4>{translate('customer_title')}</h4>
                            <div className={styles.info}>
                                <p><Phone width={iconSize} /></p>
                                <p>{customer?.phone}</p>
                            </div>
                            <div className={styles.info}>
                                <p><Mail width={iconSize} /></p>
                                <p>{customer?.email}</p>
                            </div>
                            <div className={styles.info}>
                                <p><Clock width={iconSize} /></p>
                                <p>{intl.locale === 'en' ? 
                                    customer?.open.map((item, i) => (
                                        <span key={i}>{formatOpening(i, item)}</span>
                                    )) 
                                    : 
                                    customer?.open_zh.map((item, i) => (
                                        <span key={i}>{item}</span>
                                    ))}
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* important notice */}
                    <div className={styles.notice}>
                        <p weight='bold' mode='important'>{translate('notice_title').toUpperCase()}:</p>
                        <p mode='important'>{translate('notice_message')}</p>
                    </div>
                </section>

                {/* decoration */}
                <section className={styles.waves}>
                    <div><Image src={width >= deviceBreakpoints.tablet ? WaveLarge : WaveSmall} alt='waves' /></div>
                </section>
            </main>

            <Footer />
        </div>
    );
}

export default Contact;
