import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';
import { Phone, Mail, Clock } from 'react-feather';

import WaveLarge from '../public/decorations/wave-large.png';
import WaveSmall from '../public/decorations/wave-small.png';

import { translate } from '../resources/Translations';
import styles from '../styles/Contact.module.css';

import { getContactInfo } from './api/services';
import { deviceBreakpoints } from '../components/utilities/config';
import { useWindowDimensions } from '../components/utilities/customHooks';

import Header from '../components/Header';
import Footer from '../components/Footer';

function Contact() {
    const iconSize = 18;
    const { width, height } = useWindowDimensions();

    const [ contacts, setContacts ] = useState([]);
    const ordering = contacts.find(item => item.id === 'ordering');
    const customer = contacts.find(item => item.id === 'customer');

    useEffect(() => {
        getContactInfo().then(content => setContacts(content));
    }, []);

    return (
        <div>
            <Head>
                <title>Italian Tomato | Contact Us</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <main className={styles.container}>
                <section className={styles.content}>
                    <h1>{translate('page_title')}</h1>

                    <div>
                        <div>
                            <h4>{translate('ordering_title')}</h4>
                            <div className={styles.info}>
                                <p><Phone width={iconSize} /></p>
                                <p>{ordering?.phone}</p>
                            </div>
                            <div className={styles.info}>
                                <p><Mail width={iconSize} /></p>
                                <p>
                                    {ordering?.email}
                                    <span style={{ fontSize: '0.85em', marginTop: '-4px' }}>({translate('ordering_note')})</span>
                                </p>
                            </div>
                            <div className={styles.info}>
                                <p><Clock width={iconSize} /></p>
                                <p>{ordering?.open.map((item, i) => (<span key={i}>{item}</span>))}</p>
                            </div>
                        </div>
                        <div>
                            <h4>{translate('customer_title')}</h4>
                            <div className={styles.info}>
                                <p><Phone width={iconSize} /></p>
                                <p>{customer?.phone}</p>
                            </div>
                            <div className={styles.info}>
                                <p><Mail width={iconSize} /></p>
                                <p>{customer?.email}</p>
                            </div>
                            <div className={styles.info}>
                                <p><Clock width={iconSize} /></p>
                                <p>{customer?.open.map((item, i) => (<span key={i}>{item}</span>))}</p>
                            </div>
                        </div>
                    </div>

                    <div className={styles.notice}>
                        <p weight='bold' mode='important'>{translate('notice_title').toUpperCase()}:</p>
                        <p mode='important'>{translate('notice_message')}</p>
                    </div>
                </section>

                <section className={styles.waves}>
                    <span><Image src={width >= deviceBreakpoints.tablet ? WaveLarge : WaveSmall} alt='wave-light-green' /></span>
                </section>
            </main>

            <Footer />
        </div>
    )
}

export default Contact;
