import Head from 'next/head';
import { useState } from 'react';
import { useRouter } from 'next/router';

import { translate } from '../translations/Translations';
import { Checkbox, Radio, Dropdown } from '../components/Utilities';

function Dummy() {
    const router = useRouter();

    const dropdownList = [ 
        { label: 'Option 1', value: 1 },
        { label: 'Option 2', value: 2 },
    ];
    const [ selectedDropdown1, setSelectedDropdown1 ] = useState({ label: '', value: 0 });
    const [ selectedDropdown2, setSelectedDropdown2 ] = useState({ label: '', value: 0 });
    const [ selectedDropdown3, setSelectedDropdown3 ] = useState({ label: '', value: 0 });

    const [ checklist1, setChecklist1 ] = useState(false);
    const [ checklist2, setChecklist2 ] = useState(false);

    const [ selectedRadio, setSelectedRadio ] = useState('one');

    return (
        <div>
            <Head>
                <title>Italian Tomato | Design System</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                <section>
                    <h1 mode='hero'>{translate('hello')}</h1>
                    <h1>{translate('welcome')}</h1>

                    <h2>Heading 2</h2>

                    <h3>Heading 3</h3>

                    <h4>Heading 4</h4>
                    <h4 deco='underline'>Heading 4</h4>

                    <h5>Heading 5</h5>
                    <h5 status='active'>Heading 5</h5>
                    <h5 weight='regular'>Heading 5</h5>
                    <h5 weight='regular' status='active'>Heading 5</h5>

                    <h6>Heading 6</h6>

                    <p>Paragraph</p>
                    <p weight='medium'>Paragraph</p>
                    <p weight='bold'>Paragraph</p>

                    <a href='#abc'>link</a>
                </section>

                <button>Button</button>

                <input type='text' placeholder='Enter text' />

                <section style={{ backgroundColor: 'var(--lightGreen)', padding: '15px', margin: '10px' }}>
                    <input type='text' placeholder='Enter text' />
                </section>

                <section>
                    <Dropdown content={dropdownList} value={selectedDropdown1} placeholder='--- Please Select ---' onChange={setSelectedDropdown1} />
                    <Dropdown content={dropdownList} value={selectedDropdown2} placeholder='--- Please Select ---' searchable={false} onChange={setSelectedDropdown2} />
                    <Dropdown content={dropdownList} value={selectedDropdown3} placeholder='Read only' searchable={false} disabled={true} onChange={setSelectedDropdown3} />
                </section>

                <section>
                    <Checkbox label='Checkbox 1' checked={checklist1} onChange={setChecklist1} />
                    <Checkbox label='Checkbox 2' checked={checklist2} onChange={setChecklist2} />
                </section>

                <section>
                    <Radio label='Radio 1' value={'one'} name='radio' checked={selectedRadio} onChange={setSelectedRadio} />
                    <Radio label='Radio 2' value={'two'} name='radio' checked={selectedRadio} onChange={setSelectedRadio} />
                </section>
            </main>

            <footer>
                &copy; 2021 Chawisa Lo. All rights reserved.
            </footer>
        </div>
    );
}

export default Dummy;