import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';

import AppleStore from '../public/apple-store-icon.png';
import GooglePlay from '../public/google-play-icon.png';
import Cake from '../public/home/gateau-aux-fraises.png';
import BubbleMedium from '../public/home/bubble-medium-green.png';
import BubbleLight from '../public/home/bubble-light-green.png';

import { translate } from '../resources/Translations';
import styles from '../styles/Home.module.css';

import { getProductsByTag } from './api/services';
import { useWindowOffset } from '../components/utilities/customHooks';

import Header from '../components/Header';
import Footer from '../components/Footer';

import ProductCard from '../components/subcomponents/ProductCard';
import StepCard from '../components/subcomponents/StepCard';

// TODO: routing

function Home() {
    const router = useRouter();
    const { offsetX, offsetY } = useWindowOffset();
    const [ products, setProducts ] = useState([]);

    console.log(offsetY);
    
    useEffect(() => {
        getProductsByTag('best-selling').then(content => setProducts(content));
    }, []);

    return (
        <div>
            <Head>
                <title>Italian Tomato</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header />

            <main className={styles.container}>
                <section className={styles.hero}>
                    <div className={styles.heroText}>
                        <h1 mode='hero'>{translate('hero_title')}</h1>
                        <p>{translate('hero_description')}</p>
                        <button>{translate('order_now')}</button>
                    </div>

                    <div className={styles.heroVisual}>
                        <span name='bubble2'>
                            <Image src={BubbleLight} alt='gateau-aux-fraises-bubble-2' />
                        </span>
                        <span name='bubble1'>
                            <Image src={BubbleMedium} alt='gateau-aux-fraises-bubble-1' />
                        </span>
                        <span name='cake'>
                            <Image src={Cake} alt='gateau-aux-fraises' />
                        </span>
                    </div>
                </section>

                <section className={styles.products}>
                    <h4 deco='underline'>{translate('best_selling')}</h4>

                    <div>
                        <ProductCard product={products[0]} />
                        <ProductCard product={products[1]} />
                        <ProductCard product={products[2]} />
                        <ProductCard product={products[3]} />
                    </div>
                </section>

                <section className={styles.ordering}>
                    <h4 deco='underline'>{translate('ordering')}</h4>

                    <div>
                        <StepCard stepNumber={1} />
                        <StepCard stepNumber={2} />
                        <StepCard stepNumber={3} />
                        <StepCard stepNumber={4} />
                    </div>
                </section>

                <section className={styles.membership}>
                    <h4 deco='underline'>{translate('membership')}</h4>

                    <div>
                        <div className={styles.membershipIntro}>
                            <div>
                                <h2>{translate('become_member_title')}</h2>
                                <p>{translate('become_member_answer')}</p>
                                <span className={styles.membershipButton}>
                                    <button>
                                        <span style={{ marginTop: '-2px' }}><Image src={AppleStore} alt='iconmonstr-apple-store-icon' /></span>
                                        APP STORE
                                    </button>
                                    <button>
                                        <span><Image src={GooglePlay} alt='iconmonstr-google-play-icon' /></span>
                                        GOOGLE PLAY
                                    </button>
                                </span>
                            </div>
                            <div>
                                <h2>{translate('become_vip_member_title')}</h2>
                                <p>{translate('become_vip_member_answer')}</p>
                            </div>
                            <div>
                                <h2>{translate('points_work_title')}</h2>
                                {translate('points_work_answer').split('\n').map((item, i) => (<p key={i}>{item}</p>))}
                            </div>
                        </div>
                        <div className={styles.membershipDetails}>
                            <div className={styles.membershipCard}>
                                <h2>{translate('membership_basic_title')}</h2>
                                {translate('basic_offer').split('\n').map((item, i) => (
                                    item.includes('*') ? <p key={i} weight='medium'>{item.replace('*', '')}</p> : <p key={i}>{item}</p>
                                    ))}
                            </div>
                            <div className={styles.membershipCard}>
                                <h2>{translate('membership_vip_title')}</h2>
                                {translate('vip_offer').split('\n').map((item, i) => (
                                    item.includes('*') ? <p key={i} weight='medium'>{item.replace('*', '')}</p> : <p key={i}>{item}</p>
                                    ))}
                            </div>
                        </div>
                    </div>
                </section>
            </main>

            <Footer />
        </div>
    );
}

export default Home;