import Head from 'next/head';
import { useState } from 'react';
import { useRouter } from 'next/router';

import { translate } from '../resources/Translations';
import { Checkbox, Radio, Dropdown } from '../resources/Element';
import styles from '../styles/Home.module.css';

function Home() {
    const router = useRouter();

    return (
        <div className={styles.container}>
            <Head>
                <title>Template 1</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
            </main>

            <footer className={styles.footer}>
                &copy; {translate('footer.copyright')}
            </footer>
        </div>
    );
}

export default Home;