import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

import ItalianTomatoLogo from '../public/brands/italian-tomato.png';
import ItalianTomatoCover from '../public/brands/italian-tomato-cover.png';
import TomatoCafeLogo from '../public/brands/tomato-cafe.png';
import TomatoCafeCover from '../public/brands/tomato-cafe-cover.png';
import CafeGrillLogo from '../public/brands/cafe-grill.png';
import CafeGrillCover from '../public/brands/cafe-grill-cover.png';
import FariBeurreLogo from '../public/brands/fari-beurre.png';
import FariBeurreCover from '../public/brands/fari-beurre-cover.png';
import WasabouLogo from '../public/brands/wasabou.png';
import WasabouCover from '../public/brands/wasabou-cover.png';

import { translate } from '../translations/Translations';
import styles from '../styles/Brands.module.css';

import { useWindowDimensions } from '../utilities/customHooks';

import Header from '../components/Header';
import Footer from '../components/Footer';

// TODO: download menu

function Brands() {
    const { width, height } = useWindowDimensions();
    const [ sidebar, setSidebar ] = useState(false);
    const [ hover, setHover ] = useState([false, false, false, false, false]);

    const upateHover = (index, value) => {
        let newHover = [ ...hover ];
        newHover[index] = value;
        setHover(newHover);
    };

    return (
        <div style={{ height: `${height}px`, width: '100vw', overflow: sidebar ? 'hidden' : 'visible' }}>
            <Head>
                <title>Italian Tomato | Our Brands</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Header open={sidebar} setOpen={setSidebar} />

            <main className={styles.container}>
                <h1>{translate('page_title')}</h1>

                {/* italian tomato */}
                <section>
                    <div>
                        <h4 deco='underline'>ITALIAN TOMATO</h4>
                        <p>{translate('italian_tomato')}</p>
                    </div>
                    <div name='imageAfter' onMouseEnter={() => upateHover(0, true)} onMouseLeave={() => upateHover(0, false)}>
                        <div className={styles.cover} hover={hover[0] ? 'true' : 'false'}>
                            <Image src={ItalianTomatoCover} alt='italian-tomato-cover' />
                        </div>
                        <div className={styles.logo} style={{ opacity: hover[0] ? '1' : '0', width: '170px' }}>
                            <Image src={ItalianTomatoLogo} alt='italian-tomato' />
                        </div>
                    </div>
                </section>
                
                {/* italian tomato cafe */}
                <section className={styles.greenBackground}>
                    <div name='imageBefore' onMouseEnter={() => upateHover(1, true)} onMouseLeave={() => upateHover(1, false)}>
                        <div className={styles.cover} hover={hover[1] ? 'true' : 'false'}>
                            <Image src={TomatoCafeCover} alt='italian-tomato-cafe-cover' />
                        </div>
                        <div className={styles.logo} style={{ opacity: hover[1] ? '1' : '0' }}>
                            <Image src={TomatoCafeLogo} alt='italian-tomato-cafe' />
                        </div>
                    </div>
                    <div>
                        <h4 deco='underline'>ITALIAN TOMATO CAFÉ</h4>
                        <p>{translate('tomato_cafe')}</p>
                    </div>
                </section>

                {/* cafe and grill italian tomato */}
                <section>
                    <div>
                        <h4 deco='underline'>CAFE &amp; GRILL ITALIAN TOMATO</h4>
                        <p>{translate('cafe_grill')}</p>
                    </div>
                    <div name='imageAfter' onMouseEnter={() => upateHover(2, true)} onMouseLeave={() => upateHover(2, false)}>
                        <div className={styles.cover} hover={hover[2] ? 'true' : 'false'}>
                            <Image src={CafeGrillCover} alt='cafe-grill-italian-tomato-cover' />
                        </div>
                        <div className={styles.logo} style={{ opacity: hover[2] ? '1' : '0', width: '260px' }}>
                            <Image src={CafeGrillLogo} alt='cafe-grill-italian-tomato' />
                        </div>
                    </div>
                </section>
                
                {/* fari beurre */}
                <section className={styles.greenBackground}>
                    <div name='imageBefore' onMouseEnter={() => upateHover(3, true)} onMouseLeave={() => upateHover(3, false)}>
                        <div className={styles.cover} hover={hover[3] ? 'true' : 'false'}>
                            <Image src={FariBeurreCover} alt='fari-beurre-cover' />
                        </div>
                        <div className={styles.logo} style={{ opacity: hover[3] ? '1' : '0' }}>
                            <Image src={FariBeurreLogo} alt='fari-beurre' />
                        </div>
                    </div>
                    <div>
                        <h4 deco='underline'>FARI BEURRE</h4>
                        <p>{translate('fari_beurre')}</p>
                    </div>
                </section>

                {/* wasabou kamamur yumemiya */}
                <section>
                    <div>
                        <h4 deco='underline'>WASABOU KAMAKUR YUMEMIYA</h4>
                        <p>{translate('wasabou')}</p>
                    </div>
                    <div name='imageAfter' onMouseEnter={() => upateHover(4, true)} onMouseLeave={() => upateHover(4, false)}>
                        <div className={styles.cover} hover={hover[4] ? 'true' : 'false'}>
                            <Image src={WasabouCover} alt='wasabou-kamakur-yumemiya-cover' />
                        </div>
                        <div className={styles.logo} style={{ opacity: hover[4] ? '1' : '0' }}>
                            <Image src={WasabouLogo} alt='wasabou-kamakur-yumemiya' />
                        </div>
                    </div>
                </section>
            </main>

            <Footer />
        </div>
    );
}

export default Brands;
